apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcazurewebapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PCAzureWebApi
  template:
    metadata:
      labels:
        app: PCAzureWebApi
    spec:
      containers:
      - name: dockersamplerepos
        image: 848863acr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: pcazurewebapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PCAzureWebApi